name: CD

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: change Directory
        run: cd UI/
      - name: Build with Maven
        run: mvn install
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: target
          path: UI/target

  dockerize:
    if: success()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:11}
      - name: change Directory
        run: cd UI/
      - name: Print working directory
        run: pwd
      - name: Build the Docker image
        run: docker build -t thoughtworksindia/hygieia-ui:${{ env.RELEASE_VERSION }} -t thoughtworksindia/hygieia-ui:latest .
      - name: Login to docker repo
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish the Docker image
        run: docker push thoughtworksindia/hygieia-ui
